apiVersion: v1
kind: Service
metadata:
  name: featureflag-svc
  labels:
    app: otokocfeatureflag
    service: featureflag
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: featureflag